### ISSUE TITLE
Python (SciPy) port?

### ISSUE THREAD

**Issue by BradKML** [pachadotdev/kendallknight#1]
Sorry for asking, but if this implementation is fast, shouldn't this be included in SciPy as well? Would be very useful for toy statistics in Python.
P.S. found an older version of "efficient Kendall" https://github.com/looschen/fastkendall https://github.com/MoseleyBioinformaticsLab/ICIKendallTau

Note: 
- PyTorch implementation https://gist.github.com/ili3p/f2b38b898f6eab0d87ec248ea39fde94
- Python + C port https://github.com/alexy/katz/blob/master/kendall/fastkendalltau.py
- SciPy may have been stuck with this issue https://github.com/scipy/scipy/issues/1526
- Python + Rust https://github.com/Dicklesworthstone/fast_vector_similarity
- Python? https://github.com/mmhs013/pyMannKendall

**Comment by pachadotdev** [comment]
> Sorry for asking, but if this implementation is fast, shouldn't this be included in SciPy as well? Would be very useful for toy statistics in Python. P.S. found an older version of "efficient Kendall" https://github.com/looschen/fastkendall https://github.com/MoseleyBioinformaticsLab/ICIKendallTau
> 
> Note:
> 
>     * PyTorch implementation https://gist.github.com/ili3p/f2b38b898f6eab0d87ec248ea39fde94
> 
>     * Python + C port https://github.com/alexy/katz/blob/master/kendall/fastkendalltau.py
> 
>     * SciPy may have been stuck with this issue [Fast (O(n log(n)) ) implementation of Kendall's Tau (Trac #999) scipy/scipy#1526](https://github.com/scipy/scipy/issues/1526)
> 
>     * Python + Rust https://github.com/Dicklesworthstone/fast_vector_similarity
> 
>     * Python? https://github.com/mmhs013/pyMannKendall

As far as I understand, SciPy implementation is already O(n log(n)) and is therefore comparable to this R implementation. Please correct me if I'm wrong
